language: cpp

osx_image: xcode10.2

sudo: false

addons:
    apt:
        packages:
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
            - gcc-multilib
            - g++-multilib

os:
    - linux
    - osx

branches:
    only:
        - /^v[0-9].*$/
        - master

script: scripts/travis.sh
